In [1]:
from sklearn.linear_model import LogisticRegression

import pandas as pd
import numpy as np
import joblib

from sklearn.metrics import roc_auc_score


In [5]:
df = pd.read_csv('df_att.csv')
target = 'Heart Disease'

y = df[target]


In [2]:
oof_logreg = np.load('oof_logreg.npy')
oof_logreg

array([0.99710485, 0.01750592, 0.01860907, ..., 0.9498322 , 0.4821261 ,
       0.00480656], shape=(630000,))

In [3]:
oof_cbc = np.load('oof_preds_catboost.npy')
oof_cbc

array([0.99694412, 0.00789116, 0.01110667, ..., 0.87389872, 0.4965508 ,
       0.00338819], shape=(630000,))

In [4]:
oof_mlpc = np.load('oof_mlpc_preds.npy')

oof_mlpc

array([0.99705674, 0.01093415, 0.01761819, ..., 0.94724442, 0.44035608,
       0.0033776 ], shape=(630000,))

In [6]:
roc_auc_score(y, oof_logreg), roc_auc_score(y, oof_cbc), roc_auc_score(y, oof_mlpc)


(0.9526805753591894, 0.9554896500502426, 0.9532010658397945)