In [11]:
import pandas as pd
import numpy as np

from sklearn.neural_network import MLPClassifier
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder


def data_cleaning(df):
    df['Sex'] = list(map(lambda x: 'M' if x==1 else 'F', df['Sex']))
    #Transforming into category, thus 0 and 1 doesn't have distance interpretation on sex
    
    df['Chest pain type'] = list(map(lambda x: 'Light' if x==1 else 'Common' if x==2 else 'Hard' if x==3 else 'Dangerous', df['Chest pain type']))
    #Transforming into category, same reason
    
    df['FBS over 120'] = list(map(lambda x: 'Y' if x==1 else 'N', df['FBS over 120']))
    #Transforming into category, same reason
    
    df['Exercise angina'] = list(map(lambda x: 'Y' if x==1 else 'N', df['Exercise angina']))
    # Transforming into category, same reason
    
    df['Slope of ST'] = list(map(lambda x: 'Upsloping' if x==1 else 'Flat' if x==2 else 'Downsloping', df['Slope of ST']))
    # Transforming into category, same reason
    
    df['EKG results'] = list(map(lambda x: 'N' if x in [0,1] else 'P', df['EKG results']))
    # Merging 0 and 1 to 'N' thus 0 and 1 have the same relation with Heart Disease and, transforming into category
    # thus, here also, there's no distance relation between 0, 1 and 2
    return df


In [7]:
target = 'Heart Disease'
df = pd.read_csv('df_att.csv')
X = df.drop(target, axis=1)
y = df[target]

cat_features = X.select_dtypes(exclude='number').columns.tolist()
num_features = X.select_dtypes(include='number').columns.tolist()

test = pd.read_csv('test.csv')

test = data_cleaning(test)

test

id  Age Sex  ... Slope of ST  Number of vessels fluro  Thallium
0       630000   58   M  ...        Flat                        3         3
1       630001   55   F  ...   Upsloping                        0         3
2       630002   54   M  ...        Flat                        3         7
3       630003   44   F  ...   Upsloping                        0         3
4       630004   43   M  ...        Flat                        0         7
...        ...  ...  ..  ...         ...                      ...       ...
269995  899995   58   M  ...   Upsloping                        0         7
269996  899996   58   M  ...        Flat                        0         3
269997  899997   63   M  ...   Upsloping                        0         3
269998  899998   59   M  ...   Upsloping                        0         3
269999  899999   42   M  ...   Upsloping                        1         3

[270000 rows x 14 columns]

In [12]:
preprocessor = ColumnTransformer(
    transformers =[
        ("num", StandardScaler(), num_features),
        ("cat", OneHotEncoder(handle_unknown='ignore'), cat_features)
    ]
)

preprocessor.fit(X)
X = preprocessor.transform(X)

test = preprocessor.transform(test)
X, test

(array([[ 0.46792102,  1.43582185, -0.17848981, ...,  0.        ,
          1.        ,  0.        ],
        [-0.25879726, -0.36708803,  2.37483653, ...,  0.        ,
          0.        ,  1.        ],
        [ 0.22568159,  1.97001737, -1.69267171, ...,  0.        ,
          0.        ,  1.        ],
        ...,
        [ 1.55799844, -0.03321583,  0.89034447, ...,  0.        ,
          0.        ,  1.        ],
        [-0.25879726,  0.63452857, -1.36608346, ...,  0.        ,
          0.        ,  1.        ],
        [-0.37991697, -0.03321583, -1.36608346, ...,  0.        ,
          0.        ,  1.        ]], shape=(630000, 22)),
 array([[ 0.46792102, -0.70096023,  1.27631241, ...,  0.        ,
          1.        ,  0.        ],
        [ 0.10456188, -0.70096023, -1.06918505, ...,  0.        ,
          0.        ,  1.        ],
        [-0.01655783, -0.70096023,  0.68251558, ...,  0.        ,
          1.        ,  0.        ],
        ...,
        [ 1.07351959, -1.50225352,

In [15]:
params = {'hidden_layer_sizes': (128,), 'alpha': 5.894589851301599e-05, 'learning_rate_init': 0.0007594934857959463, 'activation': 'relu'}

In [16]:
model = MLPClassifier(**params)
model

MLPClassifier(alpha=5.894589851301599e-05, hidden_layer_sizes=(128,),
              learning_rate_init=0.0007594934857959463)

In [17]:
model.fit(X, y)

MLPClassifier(alpha=5.894589851301599e-05, hidden_layer_sizes=(128,),
              learning_rate_init=0.0007594934857959463)

In [18]:
MLPCpreds = model.predict_proba(test)[:, 1]
MLPCpreds

array([0.93394057, 0.00404241, 0.99005345, ..., 0.05194783, 0.28453174,
       0.02419166], shape=(270000,))